const list = [
    {
      id: 1,
      title: "The Sun Also Rises",
      author: "by Ernest Hemingway",
      publish: "25 April 1926",
      price: 89,
      img: "https://www.rd.com/wp-content/uploads/2020/01/87_The-Sun-Also-Rises-by-Ernest-Hemingway-via-amazon.jpg?resize=700,700",
      amount: 1,
    },
    {
      id: 2,
      title: "The Road",
      author: "by Cormac McCarthy",
      publish: "1 September 2006",
      price: 98,
      img: "https://www.rd.com/wp-content/uploads/2020/01/84_The-Road-by-Cormac-McCarthy-via-amazon.jpg?resize=700,700",
      amount: 1,
    },
    {
      id: 3,
      title: "A Promised Land",
      author: "by Barack Obama",
      publish: "17 November 2020",
      price: 143,
      img: "https://images-eu.ssl-images-amazon.com/images/I/41nzI1lhIVL._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
      amount: 1,
    },
    {
      id: 4,
      title: "Control Your Mind",
      author: "by Eric Robertson",
      publish: "25 April 2018",
      price: 57,
      img: "https://m.media-amazon.com/images/I/518K9-ZXaaL._SL500_.jpg",
      amount: 1,
    },
    {
      id: 5,
      title: "Read People like a Book",
      author: "by Patrick King",
      publish: "1 January 2018",
      price: 149,
      img: "https://m.media-amazon.com/images/I/41F-TF5mDzL._SL500_.jpg",
      amount: 1,
    },
    {
      id: 6,
      title: "WINGS OF FIRE",
      author: "by KALAM ABDUL",
      publish: "30 September 2020",
      price: 135,
      img: "https://images-na.ssl-images-amazon.com/images/I/91yv7Zkg+dL.jpg",
      amount: 1,
    },
    {
      id: 7,
      title: "Believe in Yourself",
      author: "by Dr. Joseph Murphy",
      publish: "1 January 2021",
      price: 693,
      img: "https://images-na.ssl-images-amazon.com/images/I/41o5PJi5v3L._SX327_BO1,204,203,200_.jpg",
      amount: 1,
    },
    {
      id: 8,
      title: "Don'T Read This Book",
      author: "by Benjamin Gorman",
      publish: "6 December 2020",
      price: 2133,
      img: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTERRgCsYJR9iZ27vLJ4qwcVZd7btRnx1ZjxCuWj-BVT7hQ4N3mwnlxY68Xo-LFdGTZOq4PAvWqTbvMYPTjfPLTxyyXEqTaOvLvNFDKDtk&usqp=CAE",
      amount: 1,
    },
    {
      id: 9,
      title: "THE GOOD BOOK",
      author: "by RICHARD HOLLOWAY",
      publish: "Target Publications",
      price: 195,
      img: "https://bc-img.s3.ap-south-1.amazonaws.com/images/cover/bc/9781783780266.jpg",
      amount: 1,
    },
    {
      id: 10,
      title: "Where the Sidewalk Ends",
      author: "by Shel Silverstein",
      publish: "1 September 1974",
      price: 86,
      img: "https://www.rd.com/wp-content/uploads/2020/01/97_Where-the-Sidewalk-Ends-by-Shel-Silverstein-via-amazon.jpg?resize=700,700",
      amount: 1,
    },
    {
      id: 11,
      title: "Angela’s Ashes",
      author: "by Frank McCourt",
      publish: "14 December 1996",
      price: 120,
      img: "https://www.rd.com/wp-content/uploads/2020/01/10_Angelas-Ashes-A-Memoir-by-Frank-McCourt.jpg.jpg?resize=700,700",
      amount: 1,
    },
    {
      id: 12,
      title: "Love Medicine",
      author: "by Louise Eldrich",
      publish: "1 January 2015",
      price: 1984,
      img: "https://www.rd.com/wp-content/uploads/2020/01/35_Love-Medicine-by-Louise-Eldrich-via-amazon.jpg?resize=700,700",
      amount: 1,
    },
  ];
  
  export default list;